#!/bin/bash

#Environment Variables required to import Exchange Asset to API Manager
export MULE_PORT="${MULE_PORT:-"8081"}"
export MULE_SCHEME="${MULE_SCHEME:-"https"}"
export MULE_TYPE="${MULE_TYPE:-"raml"}"
export MULE_VERSION4ORABOVE="${MULE_VERSION4ORABOVE:-"true"}"
export MULE_DEPLOYMENTTYPE="${MULE_DEPLOYMENTTYPE:-"hybrid"}"
export MULE_REMOVE_STALE_POLICIES="${MULE_REMOVE_STALE_POLICIES:-"true"}"
export MODIFYJAR="${MODIFYJAR:-"true"}"
#export ANYPOINT_OFFLINE_CONVERTER="${ANYPOINT_OFFLINE_CONVERTER:-"true"}"

export MULE_PUTASSETTAGS="${MULE_PUTASSETTAGS:-"true"}"
export MULE_PUTASSETCATEGORIES="${MULE_PUTASSETCATEGORIES:-"true"}"
export MULE_CHECKASSETTAGS="${MULE_CHECKASSETTAGS:-"true"}"
export MULE_CHECKASSETCATEGORIES="${MULE_CHECKASSETCATEGORIES:-"true"}"
export MULE_PYTHONSSLVERIFICATIONREQUIRED="${MULE_PYTHONSSLVERIFICATIONREQUIRED:-"false"}"
export MULE_REMOVE_STALE_SLA="${MULE_REMOVE_STALE_SLA:-"false"}"

export MULE_API_NAME_PROXY_SUBPATH="${MULE_API_NAME_PROXY_SUBPATH:-$MULE_ASSETIDENTIFIER}"
